- name: Prepare the stuff
  hosts: localhost
  gather_facts: false

  vars:
    aap_hostname: "{{ aap }}"
    aap_username: "{{ user }}"
    aap_password: "{{ pass }}"
    aap_ve

  pre_tasks:
    - name: create random string
      set_fact:
        random_suffix: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_lowercase,digits length=6') }}"
  
    - name: prepare inventory
      set_fact:
        # Create the single inventory name
        target_inventory_name: "tmpinventory_{{ random_suffix }}"
        
        # Transform onhosts into a list of host objects for that inventory
        controller_hosts: >-
          {{
            onhosts | map('regex_replace', '^(.*)$', {
              'name': '\\1',
              'inventory': 'tmpinventory_' ~ random_suffix,
              'enabled': true
            }) | list
          }}

  roles:
    - {role: infra.aap_configuration.controller_hosts, when: controller_hosts is defined}
